version: '3.1'


services:
  database:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
  backend:
    build: ./todonotes
    privileged: true
    ports:
      - 8080:8080
    command:
      bash -c "python manage.py migrate &&
      python manage.py create_user &&
      gunicorn todonotes.wsgi -b 0.0.0.0:8080"
    depends_on:
      - database
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
