# Generated by Django 3.2.8 on 2022-03-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_alter_todo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='TODO.project'),
        ),
    ]
